CREATE TRIGGER TRG_ATUALIZAR_STAUTS_SOLICITACAO
ON SOLICITACAO
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @IDPSOLICITACAO INT
	DECLARE @STATUS AS VARCHAR(200)
    
    SELECT @STATUS = status_solicitacao from INSERTED
    SELECT @IDPSOLICITACAO = id_solicitacao FROM INSERTED
    
    INSERT into alteracaoSolicitacao VALUES (@IDPSOLICITACAO, @STATUS, getdate())
END   
 